### ISSUE TITLE
volo serve doesn't work

### ISSUE THREAD

**Issue by marti1125** [mozilla/mortar-app-stub#4]
when I created a project

git clone git://github.com/mozilla/mortar-app-stub.git noticias_pe
cd noticias_pe
volo serve

starting web server at http://localhost:8008

events.js:71
        throw arguments[1]; // Unhandled 'error' event
                       ^
Error: listen EADDRINUSE
    at errnoException (net.js:770:11)
    at Server._listen2 (net.js:910:14)
    at listen (net.js:937:10)
    at Server.listen (net.js:986:5)
    at Function.app.listen (/home/willy/noticias_pe/node_modules/connect/lib/proto.js:229:24)
    at Object.module.exports.serve [as run](/home/willy/noticias_pe/volofile:279:41)
    at commands.run (/usr/lib/node_modules/volo/lib/commands.js:154:37)
    at _fulfilled (/usr/lib/node_modules/volo/node_modules/q/q.js:860:32)
    at resolve.promiseSend.done (/usr/lib/node_modules/volo/node_modules/q/q.js:881:34)
    at makePromise.promise.promiseSend (/usr/lib/node_modules/volo/node_modules/q/q.js:553:9)

**Comment by fwenzel** [comment]
It actually tells you what's wrong -- just not very nicely ;)

Error: listen EADDRINUSE

means you're already using port 8008 on localhost. Possibly, you've already got another instance of `volo serve` running? Take a look at `ps aux` and see if there's a volo process you need to kill.

Otherwise, take a look at what else might be using port 8008 resolve that conflict.

Hope that helps!

**Comment by tofumatt** [comment]
We could try/catch this and listen on an alternate port; I've often got a few web app servers running at once and it'd be nice to not have to manually specify the port.
- tofumatt (Sent from mobile)

**Comment by fwenzel** [comment]
Sure, though wouldn't that result in unexpected port numbers (oh, I guess today my web app is served off port 8012)?

**Comment by jlongster** [comment]
Yeah, it might be confusing if ports automatically changed, but I'm open to figuring out a better way to handle this.

**Comment by fwenzel** [comment]
`volo serve 8088` should serve on port 8088.

**Comment by marti1125** [comment]
~/myapp(master) $volo serve 9000
starting web server at http://localhost:8008

**Comment by fwenzel** [comment]
by "should" I mean, I request that to be a feature.

**Comment by jlongster** [comment]
I think the serve command is broken in this regard and doesn't respect the port. I will patch this.

**Comment by jlongster** [comment]
This is fixed in 91a3e81 and has been pushed to all templates. Thanks!

**Comment by jlongster** [comment]
Marti, if you want to simply download the fix to your project, just copy the `volofile` file into yours.

**Comment by marti1125** [comment]
Ok, thanks
